# Generated by Django 4.2.19 on 2025-02-28 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy_expected', models.DecimalField(decimal_places=10, max_digits=15)),
                ('energy_observed', models.DecimalField(decimal_places=10, max_digits=15)),
                ('irradiation_expected', models.DecimalField(decimal_places=10, max_digits=15)),
                ('irradiation_observed', models.DecimalField(decimal_places=10, max_digits=15)),
                ('datetime', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Data Point',
                'verbose_name_plural': 'Data Points',
            },
        ),
    ]
